---
- name: Configure endpoints
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  #- name: include vars
  #  include_vars: change_request_vars.yml
  - name: Pip install certifi
    pip:
      name: certifi
      extra_args: --user --upgrade
  - name: Pip install kubernetes
    pip:
      name: kubernetes
      extra_args: --user --upgrade
  - name: Pip install openshift
    pip:
      name: openshift
      extra_args: --user --upgrade
  
  - name: Git repo pull
    git:
      repo: 'https://github.com/mdelder/f5-bd-gslb-tool.git'
      dest: ./
      version: master
  
  - name: Check output
    shell: ls

  #- name: Execute configuration
  #  script: ./src/

  #- name: Execute configuration
  #  command: ./mypythonscript.py
  #  args:
  #    chdir: ./src/...
  #   run_once: true