---
- name: Configure endpoints
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  #- name: include vars
  #  include_vars: change_request_vars.yml
  - name: Pip install pysnow
    pip:
      name: pysnow
      extra_args: --user
  - name: Find my home
    command: pwd
  
  - name: Git repo pull
    git:
      repo: 'https://github.com/mdelder/f5-bd-gslb-tool.git'
      dest: /tmp/f5
      version: master
  - name: Check output
    command: ls /tmp/f5