---
- name: Configure endpoints
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    API_DOMAIN: demo.red-chesterfield.com
    target_clusters:
      - juliet-alpha
      - juliet-bravo
    GSLB_ZONE: www-apps
    BASE_DOMAIN: 'juliet.{{API_DOMAIN}}'

  tasks:
  - debug: msg="BASE_DOMAIN={{BASE_DOMAIN}}"
    #- name: include vars
  #  include_vars: change_request_vars.yml
  #- name: Show nslookup
  #  debug: msg="{{ lookup('dig', 'multicloud-console.apps.'+item+'.demo.red-chesterfield.com').split(',') }}"
  #  loop: "{{target_clusters}}"
  - name: Generate apiEndpoint URLs
    set_fact:
      apiEndpoint: "{{ apiEndpoint|default({}) | combine({ item: 'https://api.'+ item + '.' + API_DOMAIN + ':6443' }) }}"
    loop: "{{target_clusters}}"
  - debug: msg="{{apiEndpoint}}"

  - name: Retrieve publicAddress
    set_fact:
      publicAddress: "{{ publicAddress|default({}) | combine({ item: { 'az1': lookup('dig', 'multicloud-console.apps.'+item+'.demo.red-chesterfield.com').split(',')[0], 'az2': lookup('dig', 'multicloud-console.apps.'+item+'.demo.red-chesterfield.com').split(',')[1]} }) }}"
    loop: "{{target_clusters}}"
  
  - debug: msg="{{publicAddress}}"

  - name: Pip install certifi
    pip:
      name: certifi
      extra_args: --user --upgrade
  - name: Pip install kubernetes
    pip:
      name: kubernetes
      extra_args: --user --upgrade
  - name: Pip install openshift
    pip:
      name: openshift
      extra_args: --user --upgrade
  
  - name: Git repo pull
    git:
      repo: 'https://github.com/mdelder/f5-bd-gslb-tool.git'
      dest: f5
      version: master
  
  - name: Check output
    shell: ls -R ./f5

  #- name: Execute configuration
  #  script: ./f5/src/

  #- name: Execute configuration
  #  command: ./mypythonscript.py
  #  args:
  #    chdir: ./f5/src/...
  #   run_once: true